steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - 'Dockerfile.cloud'
      - '-t'
      - 'gcr.io/fs-alert-d4f21/fx-alert:$COMMIT_SHA'
      - '.'
    id: 'build-image'

  # Push image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/fs-alert-d4f21/fx-alert:$COMMIT_SHA']
    waitFor: ['build-image']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'fx-alert'
      - '--image'
      - 'gcr.io/fs-alert-d4f21/fx-alert:$COMMIT_SHA'
      - '--region'
      - 'us-west1'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'
      - '--vpc-connector'
      - 'projects/fs-alert-d4f21/locations/us-west1/connectors/fx-alert-vpc-connector'
      - '--vpc-egress'
      - 'private-ranges-only'
      - '--memory'
      - '256Mi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '2'
      - '--concurrency'
      - '80'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=fs-alert-d4f21,ENV=${_ENV}'
options:
  logging: CLOUD_LOGGING_ONLY  # or NONE
substitutions:
  _ENV: 'prod'

images:
  - 'gcr.io/fs-alert-d4f21/fx-alert:$COMMIT_SHA'