# Use a more lightweight Node.js image
FROM node:20-slim

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install all dependencies, including devDependencies
RUN npm ci

# Copy source code
COPY . .

# Expose the port
EXPOSE 8080

# Set environment variables
ENV GOOGLE_CLOUD_PROJECT=fs-alert-d4f21 \
    ENV=dev

# Install nodemon globally for development
RUN npm install -g nodemon

# Use nodemon for development with hot reload
CMD ["nodemon", "src/index.ts"]