FROM node:20-alpine3.21

WORKDIR /usr/src/app

# Copy package files
COPY package*.json ./

# Install dependencies more efficiently
RUN npm ci --only=production --no-cache && \
    npm install -g redis ioredis @types/redis && \
    npm cache clean --force && \
    rm -rf ~/.npm

# Copy source code
COPY . .

# Expose the port
EXPOSE 8080

ENV GOOGLE_CLOUD_PROJECT=fs-alert-d4f21
ENV ENV=prod

# Use nodemon for development with hot reload
CMD ["npm", "start"]