version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "7020:7020"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=./service-account2-key.json
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - postgres
    restart: on-failure
  postgres:
    container_name: fx_alert_db
    image: postgres:15.1
    hostname: localhost
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fx_alert_db
    volumes:
      - postgres-fx-alert:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-fx-alert:
