FROM node:20

WORKDIR /usr/src/app

COPY package*.json ./

# Install dependencies with legacy peer deps
RUN npm install 
RUN npm install -g redis ioredis @types/redis
 RUN npm install -g express-validator @types/express-validator

# Copy source code
COPY . .

# Expose the port
EXPOSE 8080

ENV GOOGLE_CLOUD_PROJECT=fs-alert-d4f21
ENV ENV=dev

# Use nodemon for development with hot reload
CMD ["npm", "run", "dev"]