name: CI

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create service account key file
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository root: ${{ github.workspace }}"
          echo '${{ secrets.SERVICE_ACCOUNT_KEY }}' > ${{ github.workspace }}/service-account-key.json
          ls -la ${{ github.workspace }}/service-account-key.json
      - name: Run tests
        run: npm run test
        env:
          NODE_ENV: test
